package model.enumerations;

public enum SpellTargetType {
    AN_ENEMY_POWER, 
    TWO_IN_TWO_SQUARE,
    A_FRIENDLY_POWER,
    FRIENDLY_HERO,
    ENEMY_HERO,
    THREE_IN_THREE_SQUARE,
    ALL_ENEMY_POWERS,
    A_POWER,                // ( FRIENDLY OR ENEMY )
    ALL_FRIENDLY_POWERS,
    ALL_ENEMY_IN_COLUMN,
    AN_ENEMY_MINION_IN_EIGHT_HERO,
    A_FRIENDLY_MINION,
    AN_ENEMY_MIINON,
}
