package Enumarations;

public enum SpellName {
    TOTAL_DISARM,
    AREA_DISPEL,
    EMPOWER,
    FIREBALL,
    GOD_STRENGTH,
    HELLFIRE,
    LIGHTING_BOLT,
    MADNESS,
    ALL_DISARM,
    ALL_POISON,
    DISPEL,
    HEALTH_WITH_PROFIT,
    GHAZA_BOKHOR,
    ALL_POWER,
    ALL_ATTACK,
    WEAKENING,
    SACRIFICE,
    KINGS_GUARD,
    SHOCK
}
