package Enumarations;

public enum SpellTargetType {
    AN_ENEMY_CARD,
    TWO_IN_TWO_SQUARE,
    A_FRIENDLY_CARD,
    FRINEDLY_HERO,
    ENEMY_HERO,
    THREE_IN_THREE_SQUARE,
    ALL_ENEMY_CARDS,
    A_CARD,                 // ( FRIENDLY OR ENEMY )
    ALL_FRIENDLY_CARDS,
    ALL_ENEMY_IN_COLUMN,
    AN_ENEMY_MINION,
    A_FRIENDLY_MINIOIN,
    AN_ENEMY_MINION_IN_EIGHT_HERO
}
